# -*- coding: utf-8 -*-
"""grid_search_cv.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xoJVeNBrmHFaMyX-N4dZY4nz83cC5LAw
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

df=sns.load_dataset("iris")
df

df['species'].unique()

from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC

X=df.drop('species',axis=1)
y=df['species']

model_knn=KNeighborsClassifier()
model_svm=SVC()

from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
svm_pipeline=Pipeline([('scalar',StandardScaler()),('Classifier',model_svm)])
knn_pipeline = Pipeline([('scaler', StandardScaler()),('knn_classifer', model_knn)])

score_svm=cross_val_score(svm_pipeline, X, y, cv=5)
score_knn=cross_val_score(knn_pipeline, X, y, cv=5)
print(score_svm.mean(),"this is SVM ")
print(score_knn.mean(),"This is KNN")

#"Grid_search_cv"

from sklearn.model_selection import GridSearchCV
parameter={'Classifier__C':[1,10,20,30],'Classifier__kernel':['linear','rbf'],'Classifier__gamma':['scale','auto']}
grid = GridSearchCV(
    svm_pipeline,
    parameter,
    cv=5,
    return_train_score=True
)
grid.fit(X,y)

print("Best Parameters:", grid.best_params_)
print("Best Accuracy:", grid.best_score_)

results = pd.DataFrame(grid.cv_results_)
results

results[['param_Classifier__C','param_Classifier__gamma','param_Classifier__kernel','mean_test_score','mean_train_score']]

#grid search in kNN
knn_parameter = {
    'knn_classifer__n_neighbors': [3,5,7,9,11],
    'knn_classifer__weights': ['uniform','distance'],
    'knn_classifer__metric': ['euclidean','manhattan']
}

classifier = GridSearchCV(
    knn_pipeline,
    knn_parameter,
    cv=5,
    scoring='accuracy',
    return_train_score=True
)

classifier.fit(X,y)

print("Best Parameters:", classifier.best_params_)
print("Best Accuracy:", classifier.best_score_)
results_knn=pd.DataFrame(classifier.cv_results_)

results_knn[['param_knn_classifer__metric',	'param_knn_classifer__n_neighbors',	'param_knn_classifer__weights','mean_train_score','mean_test_score'	]]

from sklearn.model_selection import RandomizedSearchCV

classifier_r = RandomizedSearchCV(
    svm_pipeline,
    parameter,
    cv=5,
    n_iter = 4
)

classifier_r.fit(X,y)

results_r=pd.DataFrame(classifier_r.cv_results_)
results_r
#print(len(classifier_r.cv_results_['params']))
#results_r[['params', 'mean_test_score']]

#"for the KNN"

classifier_knn_r=RandomizedSearchCV(knn_pipeline,knn_parameter,cv=5,n_iter=5,return_train_score=True)

classifier_knn_r.fit(X,y)

results_knn_r=pd.DataFrame(classifier_knn_r.cv_results_)
results_knn_r

print("Best accuracy",classifier.best_score_)
print("Best param",classifier.best_params_)