# -*- coding: utf-8 -*-
"""Stacking.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uEFbt3JsqZC3G3_tI-HpRar1AwtDlBKj
"""

from sklearn.model_selection import train_test_split
from sklearn.ensemble import StackingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.neighbors import KNeighborsClassifier

df = sns.load_dataset('iris')

df.head()

X = df.drop('species', axis=1)
y = df['species']

le = LabelEncoder()
y_encoded = le.fit_transform(y)

X_train, X_test, y_train, y_test = train_test_split(X, y_encoded, test_size=0.2, random_state=42, stratify=y_encoded)

base_learners = [
    ('dt', DecisionTreeClassifier(random_state=42)),
    ('svc', SVC(probability=True, kernel='rbf', random_state=42)),
    ('lr', LogisticRegression(max_iter=1000))
]

meta_model = KNeighborsClassifier(n_neighbors=5)

stack = StackingClassifier(
    estimators=base_learners,
    final_estimator=meta_model,
    cv=5
)

stack.fit(X_train,y_train)

y_pred=stack.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
accuracy

accuracy2 = stack.score(X_test, y_test)
accuracy2