# -*- coding: utf-8 -*-
"""titanic_multiple_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1keibgV4v6GzNlLdji49BL4vpNXwtwOam
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

df=sns.load_dataset('titanic')
df.head()

df.info()

df.columns

df.drop(["deck","embark_town","alive","adult_male","class","who"],axis=1,inplace=True)
df

df.info()

df['age'].fillna(df['age'].mean(),inplace=True)

df.dropna(subset="embarked",inplace=True)

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

df.head()

df['sex']=le.fit_transform(df['sex'])
df['embarked']=le.fit_transform(df['embarked'])

df

df=df.astype(int)

X=df.drop('survived',axis=1)
y=df['survived']

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=32)

from sklearn.linear_model import LogisticRegression
logr=LogisticRegression()
logr.fit(X_train,y_train)

y_pred=logr.predict(X_test)

from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report,
    precision_score,
    recall_score,
    f1_score,
)

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", cm)

precision = precision_score(y_test, y_pred)
print("Precision:", precision)

recall = recall_score(y_test, y_pred)
print("Recall:", recall)

f1 = f1_score(y_test, y_pred)
print("F1 Score:", f1)

print("\nClassification Report")
print(classification_report(y_test, y_pred))

"KNN"
from sklearn.preprocessing import StandardScaler
scalar=StandardScaler()

X_train_scalar = scalar.fit_transform(X_train)
X_test_scalar=scalar.transform(X_test)

from sklearn.neighbors import KNeighborsClassifier
knn_model=KNeighborsClassifier(n_neighbors=5)
knn_model.fit(X_train_scalar,y_train)

y_pred_=knn_model.predict(X_test_scalar)

accuracy_score(y_pred_,y_test)

confusion_matrix(y_test,y_pred_)

"NAVIES BAYES"
from sklearn.naive_bayes import GaussianNB
NB_model=GaussianNB()
"no need of the standard scalar  "

NB_model.fit(X_train,y_train)

y_pred_NB=NB_model.predict(X_test)

accuracy_score(y_pred_NB,y_test)

confusion_matrix(y_test,y_pred_NB)

print(classification_report(y_test, y_pred_NB))

from sklearn.tree import DecisionTreeClassifier
model_DT=DecisionTreeClassifier(random_state=42)
"needed the feature scaling and we use X train scaled nd y train scaled "
model_DT.fit(X_train_scalar,y_train)

y_pred_DT=model_DT.predict(X_test_scalar)

accuracy_score(y_pred_DT,y_test)

"SVM"
from sklearn.svm  import SVC
model_SVM=SVC(kernel='rbf')
"it also use the featue scaling"
model_SVM.fit(X_train_scalar,y_train)

y_pred_SVM=model_SVM.predict(X_test_scalar)

accuracy_score(y_test,y_pred_SVM)

confusion_matrix(y_test,y_pred_SVM)

print(classification_report(y_test,y_pred_SVM))

# "NOW  THE CROSS VALIDATION "
# "using the scalar it is best "
# "The core difference is that fit_transform calculates the transformation
# "parameters and applies them to the data, while transform only applies previously calculated parameters."

df

X=df.drop('survived',axis=1)
y=df['survived']

from sklearn.model_selection import cross_val_score
from sklearn.pipeline import Pipeline
svm_pipeline=Pipeline([('scalar',StandardScaler()),("SVM",model_SVM)])
knn_pipeline = Pipeline([('scaler', StandardScaler()),('knn', knn_model)])

score=cross_val_score(svm_pipeline, X, y, cv=5,scoring='accuracy')

# Decision Tree
score1=cross_val_score(model_DT, X, y, cv=5,scoring='accuracy')

# KNN
score2=cross_val_score(knn_pipeline, X, y, cv=5,scoring='accuracy')

# Gaussian Naive Bayes
score3=cross_val_score(NB_model, X, y, cv=5,scoring='accuracy')

print(score.mean())
print(score1.mean())
print(score2.mean())
print(score3.mean())